import { pgTable, text, timestamp, boolean, serial, integer } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const medications = pgTable('medications', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), dosage: text('dosage').notNull(), frequency: text('frequency').notNull(), instructions: text('instructions'), color: text('color').notNull().default('blue'), active: boolean('active').notNull().default(true), createdAt: timestamp('created_at').notNull().defaultNow() })
export const medicationLogs = pgTable('medication_logs', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), medicationId: integer('medication_id').notNull(), scheduledAt: timestamp('scheduled_at').notNull(), takenAt: timestamp('taken_at'), status: text('status').notNull().default('scheduled'), notes: text('notes') })
export const medicationSchedules = pgTable('medication_schedules', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), medicationId: integer('medication_id').notNull(), timeOfDay: text('time_of_day').notNull(), days: text('days').notNull().default('daily'), enabled: boolean('enabled').notNull().default(true) })

export const schema = { user, session, account, verification, medications, medicationLogs, medicationSchedules }
export type Medication = typeof medications.$inferSelect
export type NewMedication = typeof medications.$inferInsert
