'use client'

import { useMemo, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { archiveMedication, createMedication } from '@/app/actions/medications'
import { takeDose, undoDose } from '@/app/actions/doses'
import { Activity, Bell, CalendarDays, Check, ChevronDown, Clock3, FileText, HeartPulse, LayoutDashboard, Menu, MoreHorizontal, Pill, Plus, Search, Settings, ShieldCheck, TrendingUp, X } from 'lucide-react'

type Medication = { id: number; name: string; dosage: string; frequency: string; instructions: string | null; color: string; active: boolean }
type Dose = { medicationId: number; status: string; scheduledAt: Date | string }

export default function MediTrackDashboard({ medications, doses, user }: { medications: Medication[]; doses: Dose[]; user: { name: string; email: string } }) {
  const [activeNav, setActiveNav] = useState('Dashboard')
  const [showAdd, setShowAdd] = useState(false)
  const [query, setQuery] = useState('')
  const [isPending, startTransition] = useTransition()
  const [message, setMessage] = useState('')
  const router = useRouter()
  const takenIds = new Set(doses.filter((dose) => dose.status === 'taken').map((dose) => dose.medicationId))
  const filtered = useMemo(() => medications.filter((m) => m.name.toLowerCase().includes(query.toLowerCase())), [medications, query])
  const initials = user.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()
  const todayTaken = takenIds.size

  function toggleDose(id: number) {
    startTransition(async () => {
      try { if (takenIds.has(id)) await undoDose(id); else await takeDose(id); setMessage(takenIds.has(id) ? 'Dose marked as scheduled.' : 'Dose logged successfully.'); router.refresh() } catch { setMessage('Unable to update this dose. Please try again.') }
    })
  }

  return <div className="min-h-screen bg-[#f6f8fb] text-[#18243a]">
    <aside className="fixed inset-y-0 left-0 z-20 hidden w-[248px] border-r border-[#e5eaf1] bg-white lg:flex lg:flex-col">
      <div className="flex h-[82px] items-center gap-3 border-b border-[#eef1f5] px-7"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#1e7b8c] text-white shadow-sm"><HeartPulse size={22} /></div><div><div className="text-[17px] font-bold tracking-tight">MediTrack</div><div className="text-[11px] font-medium text-[#8390a4]">Personal health, organized.</div></div></div>
      <div className="flex flex-1 flex-col px-4 py-7"><div className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#9aa6b7]">Workspace</div><nav className="space-y-1">{[['Dashboard', LayoutDashboard], ['Medications', Pill], ['Schedule', CalendarDays], ['History', FileText], ['Analytics', TrendingUp]].map(([label, Icon]) => <button key={label as string} onClick={() => setActiveNav(label as string)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold transition ${activeNav === label ? 'bg-[#eaf6f6] text-[#146b7a]' : 'text-[#718096] hover:bg-[#f5f7fa]'}`}><Icon size={18} strokeWidth={1.9} /><span>{label as string}</span>{label === 'Medications' && <span className="ml-auto rounded-full bg-[#edf1f5] px-2 py-0.5 text-[10px] text-[#728097]">{medications.length}</span>}</button>)}</nav><div className="mb-3 mt-9 px-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#9aa6b7]">Manage</div><nav className="space-y-1"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-[#718096] hover:bg-[#f5f7fa]"><Bell size={18} /><span>Notifications</span></button><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-[#718096] hover:bg-[#f5f7fa]"><Settings size={18} /><span>Settings</span></button></nav><div className="mt-auto rounded-xl bg-[#f3f8f8] p-4"><div className="flex items-center gap-2 text-[#1f7988]"><ShieldCheck size={17} /><span className="text-xs font-bold">Your data is private</span></div><p className="mt-2 text-[11px] leading-5 text-[#77909a]">Encrypted and only visible to you.</p></div></div>
      <div className="flex items-center gap-3 border-t border-[#eef1f5] px-5 py-5"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#dbe9ee] text-sm font-bold text-[#256b79]">{initials}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{user.name}</div><div className="truncate text-[11px] text-[#8b98aa]">{user.email}</div></div><MoreHorizontal size={17} className="text-[#9aa5b4]" /></div>
    </aside>
    <main className="lg:pl-[248px]"><header className="flex h-[82px] items-center justify-between border-b border-[#e5eaf1] bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><button className="lg:hidden"><Menu size={21} /></button><div><div className="text-xl font-bold tracking-[-0.02em]">Good morning, {user.name.split(' ')[0]} <span className="text-[#1e7b8c]">.</span></div><div className="mt-1 text-xs text-[#8592a5]">{new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(new Date())} <span className="mx-1.5 text-[#c3cad4]">·</span> Your care plan at a glance.</div></div></div><div className="flex items-center gap-3"><button className="relative rounded-lg p-2 text-[#7d8a9d] hover:bg-[#f3f6f8]"><Bell size={19} /></button><div className="hidden h-7 w-px bg-[#e8ecf1] sm:block" /><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#dbe9ee] text-xs font-bold text-[#256b79]">{initials}</div><ChevronDown size={14} className="text-[#8c98a9]" /></div></header>
      <div className="mx-auto max-w-[1380px] p-5 sm:p-8"><section className="grid gap-4 md:grid-cols-3"><StatCard icon={<Check size={18} />} tone="green" label="Today's adherence" value={`${todayTaken} / ${medications.length}`} note={medications.length ? `${Math.round((todayTaken / medications.length) * 100)}% completed` : 'No medications yet'} /><StatCard icon={<Pill size={18} />} tone="blue" label="Active medications" value={String(medications.length)} note={medications.length ? 'Care plan is up to date' : 'Add your first medication'} /><StatCard icon={<Activity size={18} />} tone="orange" label="Current streak" value="—" note="Log doses to start a streak" /></section>
        <div className="mt-7 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className="rounded-2xl border border-[#e5eaf1] bg-white p-5 shadow-[0_2px_8px_rgba(31,52,76,0.025)] sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-bold">Today's medications</h2><p className="mt-1 text-xs text-[#8a96a8]">Your active prescriptions and today&apos;s dose status.</p></div><button onClick={() => setShowAdd(true)} className="flex items-center gap-1.5 rounded-lg bg-[#1e7b8c] px-3 py-2 text-xs font-bold text-white shadow-sm transition hover:bg-[#176b7a]"><Plus size={15} /> Add medication</button></div>{message && <p className="mt-4 rounded-lg bg-[#eef8f7] px-3 py-2 text-xs font-semibold text-[#277783]">{message}</p>}<div className="mt-6 space-y-3">{filtered.length ? filtered.map((medicine) => { const isTaken = takenIds.has(medicine.id); return <div key={medicine.id} className="flex items-center gap-3 rounded-xl border border-[#edf0f4] bg-white p-3.5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e5f4f6] text-[#237e8c]"><Pill size={19} /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-sm font-bold">{medicine.name}</span>{isTaken && <span className="rounded-full bg-[#e7f6ef] px-2 py-0.5 text-[10px] font-bold text-[#31835c]">Taken</span>}</div><div className="mt-1 text-xs text-[#8491a3]">{medicine.dosage} <span className="mx-1 text-[#c1c8d1]">·</span> {medicine.frequency}</div></div><div className="hidden items-center gap-2 text-xs text-[#8592a4] sm:flex"><Clock3 size={14} /> Today</div><button disabled={isPending} aria-label={`${isTaken ? 'Undo' : 'Mark'} ${medicine.name} as taken`} onClick={() => toggleDose(medicine.id)} className={`flex h-8 w-8 items-center justify-center rounded-lg border transition ${isTaken ? 'border-[#b9dfcb] bg-[#eaf8f0] text-[#3c956a]' : 'border-[#dfe6ec] text-[#9ba7b5] hover:border-[#8fc9cf] hover:text-[#247d89]'}`}><Check size={16} /></button><button onClick={() => startTransition(async () => { await archiveMedication(medicine.id); setMessage(`${medicine.name} archived.`); router.refresh() })} className="rounded-lg p-2 text-[#b1bac5] hover:bg-[#fff2f2] hover:text-[#b45e68]" aria-label={`Archive ${medicine.name}`}><X size={15} /></button></div> }) : <div className="rounded-xl border border-dashed border-[#dfe6ec] px-6 py-12 text-center"><Pill className="mx-auto text-[#a9b6c3]" size={28} /><p className="mt-3 text-sm font-bold">Your medication list is empty</p><p className="mt-1 text-xs text-[#8794a5]">Add a prescription to begin tracking doses.</p><button onClick={() => setShowAdd(true)} className="mt-4 rounded-lg bg-[#1e7b8c] px-4 py-2 text-xs font-bold text-white">Add medication</button></div>}</div></section>
          <section className="rounded-2xl border border-[#e5eaf1] bg-white p-5 shadow-[0_2px_8px_rgba(31,52,76,0.025)] sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-bold">Adherence overview</h2><p className="mt-1 text-xs text-[#8a96a8]">Live data will appear as you log doses.</p></div><TrendingUp size={18} className="text-[#1e7b8c]" /></div><div className="mt-10 rounded-xl bg-[#f3f8f8] p-5"><div className="text-3xl font-bold text-[#1d7c88]">{medications.length ? `${Math.round((todayTaken / medications.length) * 100)}%` : '—'}</div><p className="mt-1 text-xs text-[#718a95]">Today&apos;s completion</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#75c6c0]" style={{ width: `${medications.length ? (todayTaken / medications.length) * 100 : 0}%` }} /></div></div></section></div>
        <section className="mt-6 rounded-2xl border border-[#e5eaf1] bg-white p-5 shadow-[0_2px_8px_rgba(31,52,76,0.025)] sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-base font-bold">Medication history</h2><p className="mt-1 text-xs text-[#8a96a8]">A clear record of your recent doses.</p></div><div className="relative"><Search size={15} className="absolute left-3 top-2.5 text-[#9aa6b5]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search medication" className="h-9 w-full rounded-lg border border-[#e3e8ee] bg-[#fbfcfd] pl-9 pr-3 text-xs outline-none placeholder:text-[#a5afbc] focus:border-[#8ecbd0] sm:w-48" /></div></div></section>
      </div></main>
      {showAdd && <AddMedication onClose={() => setShowAdd(false)} onSaved={() => { setShowAdd(false); setMessage('Medication added successfully.'); router.refresh() }} />}
  </div>
}

function AddMedication({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [name, setName] = useState(''); const [dosage, setDosage] = useState(''); const [frequency, setFrequency] = useState('Once daily'); const [error, setError] = useState(''); const [pending, startTransition] = useTransition(); return <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#18243a]/30 p-4 backdrop-blur-sm"><form onSubmit={(event) => { event.preventDefault(); startTransition(async () => { try { await createMedication({ name, dosage, frequency }); onSaved() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save medication.') } }) }} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Add medication</h2><p className="mt-1 text-xs text-[#8794a5]">Keep your care plan up to date.</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-[#95a0af] hover:bg-[#f3f6f8]" aria-label="Close dialog"><X size={18} /></button></div>{error && <p className="mt-4 rounded-lg bg-[#fff2f2] px-3 py-2 text-xs font-semibold text-[#b45e68]">{error}</p>}<div className="mt-6 space-y-4"><label className="block text-xs font-bold text-[#5f6e82]">Medication name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#dfe6ec] px-3 text-sm outline-none focus:border-[#7fc4c9]" placeholder="e.g. Lisinopril" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-bold text-[#5f6e82]">Dosage<input required value={dosage} onChange={(e) => setDosage(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#dfe6ec] px-3 text-sm outline-none focus:border-[#7fc4c9]" placeholder="10 mg" /></label><label className="block text-xs font-bold text-[#5f6e82]">Frequency<select value={frequency} onChange={(e) => setFrequency(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#dfe6ec] bg-white px-3 text-sm outline-none focus:border-[#7fc4c9]"><option>Once daily</option><option>Twice daily</option><option>As needed</option></select></label></div><button disabled={pending} className="mt-2 w-full rounded-lg bg-[#1e7b8c] py-3 text-sm font-bold text-white hover:bg-[#176b7a] disabled:opacity-60">{pending ? 'Saving…' : 'Save medication'}</button></div></form></div> }

function StatCard({ icon, tone, label, value, note }: { icon: React.ReactNode; tone: string; label: string; value: string; note: string }) { const tones: Record<string, string> = { green: 'bg-[#e8f7ef] text-[#3a956a]', blue: 'bg-[#e5f4f6] text-[#237e8c]', orange: 'bg-[#fff3e2] text-[#c58b35]' }; return <div className="flex items-center gap-4 rounded-2xl border border-[#e5eaf1] bg-white p-4 shadow-[0_2px_8px_rgba(31,52,76,0.025)]"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}>{icon}</div><div><div className="text-xs font-semibold text-[#8793a5]">{label}</div><div className="mt-0.5 flex items-baseline gap-2"><span className="text-xl font-bold tracking-tight">{value}</span><span className="text-[10px] font-semibold text-[#8a97a8]">{note}</span></div></div></div> }
